ollama:
  gpu:
    enabled: true
    type: "nvidia"
    number: 1
  models:
    - llama3

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: YOUR_FQDN
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: letsencrypt-prod
      hosts:
        - YOUR_FQDN

# To work reliably needs a metric for gpu load
#autoscaling:
#  enabled: true
#  minReplicas: 1
#  maxReplicas: 2

resources:
  requests:
    cpu: 3000m
  limits:
    cpu: 3800m
